version: "3.8"

services:
  app:
    build: .
    ports:
      - "8800:8800"
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
